### PR TITLE
BufferStream: Avoid needless copies

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
@glharper

**Comment by orgads** [comment]
@glharper ping?

**Comment by glharper** [comment]
@orgads, this is failing our CI testing for [this test](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f87fe1f72914987af8ca8951f7228029222f40e5/tests/SpeechRecognizerTests.ts#L1105)

With this error:
RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at ChunkedArrayBufferStream.writeStreamChunk (D:\a\_work\1\s\src\common\ChunkedArrayBufferStream.ts:31:24)
    at PushAudioInputStreamImpl.write (D:\a\_work\1\s\src\sdk\Audio\AudioInputStream.ts:110:25)
    at ReadStream.<anonymous> (D:\a\_work\1\s\tests\SpeechRecognizerTests.ts:956:24)
    at ReadStream.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at ReadStream.Readable.push (node:internal/streams/readable:245:10)
    at node:internal/fs/streams:277:14
    at FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)

**Comment by orgads** [comment]
@yoshigev ^

**Comment by orgads** [comment]
@glharper What do I need to run the tests locally? I added `secrets/TestConfiguration.ts` with a valid speech key, but most of the tests still fail.

**Comment by orgads** [comment]
Nevermind. I managed to run it using:
```
npx jest --testNamePattern=start-stop-start
```

**Comment by orgads** [comment]
I think it should be ok now, but it became too ugly. Not sure if it's worth it.

**Comment by orgads** [comment]
Closing.

**Pull request closed without merging**
