### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
@rhurey

**Comment by orgads** [comment]
@glharper @rhurey ping

**Comment by panitaxx** [comment]
would be great to see this merge. agent-base 4.3.0 used by https-proxy-agent 3.0.1 is known to cause problems in other packages. see https://github.com/TooTallNate/node-agent-base/issues/35

**Comment by glharper** [comment]
https-proxy-agent has been updated in a separate pull request.

**Pull request closed without merging**
