### PR TITLE
Use AudioWorkletNode by default for mic input

### LINKED ISSUE #391: Replace PCM Recorder script processor with audio worklet
We are getting deprecation warnings in the console due to the use of script processor in pcm recorder. We've also noticed that on lower end devices (or throttling the CPU in chrome devtools) the quality of transcriptions suffers could using an audio worklet help?

### PR DESCRIPTION
**Pull request by glharper**
Fix #391

### CODE REVIEW

**Comment by glharper** [comment]
Note there are differences between webWorkers and audioWorkletNodes. For example, webWorkers allow generated URL access on non-http URLs without generating a CORS access error, but audioWorkletNode does not. This PR keeps ScriptProcessorNode as a fallback when a CORS exception is thrown (this will be mostly be when a browser sample is opened from the filesystem, and not on an http server).

**Comment by glharper** [comment]
https://glharper-js-test.azurewebsites.net/all.html to test mic input

**Review by rhurey — APPROVED** [review]
:shipit:

**Comment by rssfrncs** [comment]
When can we expect this in a release? Thanks 🙏🏻

**Comment by glharper** [comment]
@rssfrncs Our next release, 1.18, is expected within the next two weeks. This should be included.

**Pull request merged**
