### PR TITLE
Translation: Authentication refresh token not updating

### PR DESCRIPTION
**Pull request by ej-msl**
Websocket headers using original token as when config was initialized.

### CODE REVIEW

**Comment by glharper** [comment]
@ej-msl Thanks for the PR, could you give repro steps so that I can see exactly what issue this is fixing (or add a test)?

**Comment by ej-msl** [comment]
> @ej-msl Thanks for the PR, could you give repro steps so that I can see exactly what issue this is fixing (or add a test)?

This issue occurs when using the TranslationRecognizer configured from an authorization token. A new authentication token is fetched every 9 minutes but after ~20-30 minutes the translation will stop functioning and throw the following error:
```
WebsocketMessageAdapter.ts:113 WebSocket connection to 'wss://centralus.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?from=en-US&to=de&Authorization=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJyZWdpb24iOiJjZW50cmFsdXMiLCJzdWJzY3JpcHRpb24taWQiOiJlNzVmM2JlMDRkN2M0MGVjYWU1ZTc5YTNmN2Y1MmI5MyIsInByb2R1Y3QtaWQiOiJTcGVlY2hTZXJ2aWNlcy5TMCIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIvc3Vic2NyaXB0aW9ucy9jYjRkMWU3Yi05NGEzLTRmMjMtYTEyZC1iMWZkM2IyNzNlNGEvcmVzb3VyY2VHcm91cHMvUmVzZWFyY2hSZXNvdXJjZXMvcHJvdmlkZXJzL01pY3Jvc29mdC5Db2duaXRpdmVTZXJ2aWNlcy9hY2NvdW50cy9oYXJrLXRyYW5zY3JpcHRpb24iLCJzY29wZSI6InNwZWVjaHNlcnZpY2VzIiwiYXVkIjoidXJuOm1zLnNwZWVjaHNlcnZpY2VzLmNlbnRyYWx1cyIsImV4cCI6MTYyOTEzMjA3OSwiaXNzIjoidXJuOm1zLmNvZ25pdGl2ZXNlcnZpY2VzIn0.Obnp1bi7MEBsV6ybQkR0KPD5ffmK6S4XptVwye6WU_c&X-ConnectionId=3558E9C7753B4D09ACD32EBD74B6FC96' failed: 
```

The Authorization query parameter in the above error matches the initial authorization token passed to SpeechTranslationConfig.fromAuthorizationToken at the start instead of the most recently fetched authorization token.

When testing similar code with the SpeechRecognizer (translations disabled), I do not run into any timeout issues. 

Sample Code
---
```javascript
    let authToken = "";
    let authRefreshInterval = null;
    let authRefreshDuration = 9 * 60 * 1000; // Refresh token every 9 minutes

    let serviceRegion = "centralus";
    let audioConfig = null;
    let config = null;
    let recognizer = null;

    let translationEnabled = true;
    let sourceLanguage = "en-US";
    let targetLanguage = "de";


    let fetchAuthToken = async () => {
      let response = await axios.get("http://localhost:3030/v1/authToken");
      authToken = response.data;

      // Initialize or refresh?
      if (recognizer === null) {
        authRefreshInterval = setInterval(fetchAuthToken, authRefreshDuration);
        initRecognizer();
      } else {
        recognizer.authorizationToken = authToken;
        config.authorizationToken = authToken;
      }
    };

    let initRecognizer = () => {
      audioConfig = window.SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();

      if (translationEnabled) {
        config = window.SpeechSDK.SpeechTranslationConfig.fromAuthorizationToken(authToken, serviceRegion);
        config.speechRecognitionLanguage = sourceLanguage;
        config.addTargetLanguage(targetLanguage);
        config.enableDictation();
        recognizer = new window.SpeechSDK.TranslationRecognizer(config, audioConfig);
      } else {
        config = window.SpeechSDK.SpeechConfig.fromAuthorizationToken(authToken, serviceRegion);
        config.speechRecognitionLanguage = sourceLanguage;
        config.outputFormat = window.SpeechSDK.OutputFormat.Detailed;
        config.enableDictation();
        config.requestWordLevelTimestamps();
        recognizer = new window.SpeechSDK.SpeechRecognizer(config, audioConfig);
      }

      recognizer.recognized = (s, e) => {
        let { text, translations } = e.result;
        console.log(`SourceLanguage: ${text}`);
        if (translationEnabled) {
          let translation = translations.get(targetLanguage);
          console.log(`TargetLanguage: ${translation}`);
        }
      }

      recognizer.startContinuousRecognitionAsync(
        _result => {
          console.log("Recognizer started");
        },
        error => {
          console.error(error);
        }
      );
    };
 
```

**Comment by glharper** [comment]
@ej-msl That sample code should making repro-ing this a lot faster, thank you for adding that! I'll dig into this, but I think the issue here is that:  `recognizer.authorizationToken = authToken;`
isn't working correctly for TranslationRecognizer, which is indeed a bug.

**Comment by glharper** [comment]
@ej-msl This looks good, and I have a test to add for this issue after this is checked in.

**Review by glharper — APPROVED** [review]

**Pull request merged**
