### PR TITLE
Build as es2020

### PR DESCRIPTION
**Pull request by orgads**
Much easier to debug.

### CODE REVIEW

**Comment by orgads** [comment]
Another attempt after #278. Node LTS is now 16. ES2019 is supported since Node 12.

**Comment by orgads** [comment]
Rebased and changed "2015" to "mjs" to be clearer. Please review.

**Comment by orgads** [comment]
Changed to es2020. Can you PLEASE review this? Debugging/Profiling is horrible with es6! @BrianMouncer @rhurey @glharper

**Comment by orgads** [comment]
ping?

**Review by glharper — APPROVED** [review]

**Comment by glharper** [comment]
Tested in separate PR, no issues found.

**Pull request merged**
