### PR TITLE
Enable installation from GitHub.

### LINKED ISSUE #59: Cannot install this package from GitHub.
When installing from GitHub, `prepack` script is run before dependencies are installed.
See https://github.com/npm/npm/issues/19564.

It is recommended to use `prepare` script instead:
https://docs.npmjs.com/misc/scripts

### PR DESCRIPTION
**Pull request by Domratchev**
Resolves #59

### CODE REVIEW

**Comment by Domratchev** [comment]
Sorry about the baseline. The only relevant commit here is 52e5690 (or 
5970b23).

**Comment by Domratchev** [comment]
@rhurey It is rather difficult to contribute to this repository without the ability to install the package from GitHub. Will the proposed change break anything?

**Comment by rhurey** [comment]
Can you untangle it from the ES6 work?

**Comment by Domratchev** [comment]
@rhurey Done.

**Pull request merged**
