### PR TITLE
Provide es2015 module.

### PR DESCRIPTION
**Pull request by Domratchev**
Migrate from uglify to terser.

Observe dramatic reduction in minified bundle size (about 25%).
Even better results with webpack from npm package due to enabled tree shaking.

### CODE REVIEW

**Comment by rhurey** [comment]
The change to Terser looks good.

The concern I have is changing the ECMA target is risk of breaking backward compatibility in a minor release instead of waiting for a 2.0.

**Comment by rhurey** [comment]
If you want to pull the terser change into a separate PR, or scope this one down we can take it.

**Comment by Domratchev** [comment]
@rhurey Both es5/commonjs and es2015/esnext modules are provided side-by-side.

**Comment by Domratchev** [comment]
@rhurey I've rebased with your recent commit(s).
BTW, is there a reason you are not pulling ocsp library from npm?

**Comment by rhurey** [comment]
I didn't find a way to get OCSP to work as-is if all network connections must be through a proxy server.

I could use https-proxy-agent or OCSP as the agent, but beyond that it started to turn into "duplicate a lot of OCSP's code" to get both to work together. My intent is to send a PR to OCSP that allows a user agent to be specified for cert checks and then revert to using the npm version if it's accepted.

**Comment by Domratchev** [comment]
@rhurey Why don't you fork OCSP on GitHub and refer to it in dependencies like I do to this library?
E.g.
"dependencies": {
  "microsoft-cognitiveservices-speech-sdk": "github:Domratchev/cognitive-services-speech-sdk-js#mute"
}

**Pull request merged**
