### PR TITLE
Websocket: Disable perMessageDeflate (#242)

### PR DESCRIPTION
**Pull request by orgads**
It affects performance badly.

### CODE REVIEW

**Comment by rhurey** [comment]
This strikes me as something that should have a string control property to it so we can enable / disable.

Need to plumb that down to the adapter.

**Comment by orgads** [comment]
Any progress with this?

**Comment by glharper** [comment]
See https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/271

**Comment by orgads** [comment]
Thanks

**Pull request closed without merging**
