### PR TITLE
Bump "newer" build from ES2015 to ES2018

### PR DESCRIPTION
**Pull request by orgads**
Easier to debug.

### CODE REVIEW

**Comment by orgads** [comment]
@glharper Please review

**Comment by glharper** [comment]
Unfortunately, this constitutes a breaking change according to Azure standards. We want to support node 8 in all Azure JS SDKs, and it does not support everything in ES2018.

**Comment by orgads** [comment]
Understood. Thanks.

**Comment by orgads** [comment]
The difficulties are mostly with promises and async/await.

**Pull request closed without merging**
