### PR TITLE
update https-proxy-agent lib to version that doesn't depend on proble…

### LINKED ISSUE #309: Update https-proxy-agent
The version of https-proxy-agent (3.0.1) used in this package causes conflicts with other packages because it uses agent-base version that patches https global object (see https://github.com/TooTallNate/node-agent-base/issues/35). Please update package.json or merge #224 .

### PR DESCRIPTION
**Pull request by glharper**
…matic agent-base version. Closes #309

### CODE REVIEW

**Review by brandom-msft — APPROVED** [review]
I'll take your word for it :)

**Comment by orgads** [comment]
Why not 5?

**Comment by glharper** [comment]
@orgads IIRC there was an API change in 5 that didn't play well with our TS code.

**Comment by orgads** [comment]
But I adapted it in this commit.

**Comment by glharper** [comment]
@orgads By "this commit," are you referring to [this PR?]( https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/224/files) This repo has a policy of being very conservative with our dependency version updates, so as not to cause problems for customers using older versions of (Node/TypeScript/Library Foo).

**Comment by orgads** [comment]
Yes, that's what I meant :)

Ok, I accept.

**Pull request merged**
