### PR TITLE
avatar synthesizer implementation

### PR DESCRIPTION
**Pull request by yulin-li**
avatar implementation

### CODE REVIEW

**Review by yinhew — APPROVED** [review]
I've E2E tested this code on different platforms and browsers, and it's working as expected now.

**Comment by yinhew** [comment]
sign-off

**Comment by yulin-li** [comment]
> Looking at the test results, there are a lot of tests failing that didn't fail for master. @yulin-li could you see why they are failing with this PR?

I checked, one more case `SpeechSynthesisTests.ts-testSpeechSynthesizerEvent` is failing now. I will fix it.

**Comment by glharper** [comment]
> > Looking at the test results, there are a lot of tests failing that didn't fail for master. @yulin-li could you see why they are failing with this PR?
> 
> I checked, one more case `SpeechSynthesisTests.ts-testSpeechSynthesizerEvent` is failing now. I will fix it.

I now see that everything that fails currently also is currently failing in master. Approved.

**Review by glharper — APPROVED** [review]

**Pull request merged**
