### PR TITLE
Fix IStreamChunk conflicting import bug

### PR DESCRIPTION
**Pull request by euirim**
This is my effort to resolve the following error when running this sdk on Typescript:

```
node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Stream.d.ts:3:10 - error TS2440: Import declaration conflicts with local declaration of 'IStreamChunk'.

3 import { IStreamChunk } from "./Stream";
```

I'm on Node version 10.16.3. After making the edit, my project compiles successfully.

### CODE REVIEW

**Comment by euirim** [comment]
Can someone review this? It's a quick one-line review to fix a potentially breaking bug.

**Comment by rhurey** [comment]
Working on getting a test run started. We've had some lab issues. :-(

**Comment by rhurey** [comment]
Close / Open to resolve some Azure Dev Ops links

**Comment by rhurey** [comment]
https://msasg.visualstudio.com/Skyman/_build/results?buildId=9141226

**Pull request merged**
